const contractors = [
  {
    id: 1,
    companyName: 'Quality Builders Inc.',
    contactPerson: 'John Doe',
    email: 'john@qualitybuilders.com',
    phone: '555-123-4567',
    businessNumber: 'AB123456789',
    businessType: 'corporation',
    industry: 'construction',
    address: '123 Main St, New York, NY 10001',
    serviceAreas: ['New York', 'New Jersey', 'Connecticut'],
    status: 'active',
    rating: 4.8,
    totalJobs: 245,
    completedJobs: 240,
    paymentTerms: 'net-30',
    hourlyRate: 85,
    projectRate: null,
    currency: 'USD',
    insuranceExpiry: '2025-12-31',
    certifications: [
      { id: 1, name: 'General Contractor License', expiry: '2026-06-30' },
      { id: 2, name: 'OSHA Safety Certified', expiry: '2025-09-15' }
    ],
    preferredContactMethod: 'email',
    availability: 'business-hours',
    website: 'https://qualitybuilders.com',
    description: 'Full-service construction company specializing in residential and commercial projects.',
    tags: ['construction', 'renovation', 'commercial', 'residential'],
    notes: 'Reliable contractor with excellent references.',
    referralSource: 'referral',
    createdAt: '2023-03-15T10:30:00.000Z',
    updatedAt: '2024-02-28T14:20:00.000Z',
    lastActiveAt: '2024-02-28T14:20:00.000Z',
    contractStartDate: '2023-03-20',
    contractEndDate: '2025-03-20'
  },
  {
    id: 2,
    companyName: 'Tech Solutions Pro',
    contactPerson: 'Jane Smith',
    email: 'jane@techsolutions.com',
    phone: '555-987-6543',
    businessNumber: 'TS789456123',
    businessType: 'llc',
    industry: 'it',
    address: '456 Tech Park Dr, San Francisco, CA 94107',
    serviceAreas: ['California', 'Nevada', 'Oregon'],
    status: 'active',
    rating: 4.9,
    totalJobs: 180,
    completedJobs: 178,
    paymentTerms: 'net-15',
    hourlyRate: 120,
    projectRate: null,
    currency: 'USD',
    insuranceExpiry: '2025-06-30',
    certifications: [
      { id: 1, name: 'Microsoft Certified', expiry: '2026-01-31' },
      { id: 2, name: 'AWS Solutions Architect', expiry: '2025-11-30' }
    ],
    preferredContactMethod: 'phone',
    availability: '24/7',
    website: 'https://techsolutions.com',
    description: 'IT consulting and support services for businesses of all sizes.',
    tags: ['it', 'support', 'consulting', 'cloud'],
    notes: 'Excellent emergency response time.',
    referralSource: 'website',
    createdAt: '2023-05-10T14:15:00.000Z',
    updatedAt: '2024-02-27T11:45:00.000Z',
    lastActiveAt: '2024-02-27T11:45:00.000Z',
    contractStartDate: '2023-05-15',
    contractEndDate: null
  },
  {
    id: 3,
    companyName: 'Master Electric Co.',
    contactPerson: 'Robert Johnson',
    email: 'robert@masterelectric.com',
    phone: '555-456-7890',
    businessNumber: 'EL789654123',
    businessType: 'sole-proprietor',
    industry: 'electrical',
    address: '789 Circuit Ave, Chicago, IL 60601',
    serviceAreas: ['Illinois', 'Indiana', 'Wisconsin'],
    status: 'active',
    rating: 4.7,
    totalJobs: 320,
    completedJobs: 315,
    paymentTerms: 'net-30',
    hourlyRate: 95,
    projectRate: null,
    currency: 'USD',
    insuranceExpiry: '2024-11-30',
    certifications: [
      { id: 1, name: 'Master Electrician License', expiry: '2025-08-31' },
      { id: 2, name: 'NFPA Certified', expiry: '2024-12-31' }
    ],
    preferredContactMethod: 'sms',
    availability: '24/7',
    website: null,
    description: 'Licensed electrician for residential and commercial electrical work.',
    tags: ['electrical', 'emergency', 'licensed', 'residential'],
    notes: 'Available for emergency calls.',
    referralSource: 'referral',
    createdAt: '2023-01-20T09:45:00.000Z',
    updatedAt: '2024-02-26T16:20:00.000Z',
    lastActiveAt: '2024-02-26T16:20:00.000Z',
    contractStartDate: '2023-01-25',
    contractEndDate: null
  },
  {
    id: 4,
    companyName: 'Plumbing Masters',
    contactPerson: 'Emily Williams',
    email: 'emily@plumbingmasters.com',
    phone: '555-789-0123',
    businessNumber: 'PL456123789',
    businessType: 'corporation',
    industry: 'plumbing',
    address: '321 Pipe St, Houston, TX 77002',
    serviceAreas: ['Texas', 'Louisiana', 'Oklahoma'],
    status: 'active',
    rating: 4.6,
    totalJobs: 410,
    completedJobs: 405,
    paymentTerms: 'net-30',
    hourlyRate: 80,
    projectRate: null,
    currency: 'USD',
    insuranceExpiry: '2025-03-31',
    certifications: [
      { id: 1, name: 'Master Plumber License', expiry: '2025-09-30' },
      { id: 2, name: 'Backflow Prevention Certified', expiry: '2024-10-31' }
    ],
    preferredContactMethod: 'phone',
    availability: '24/7',
    website: 'https://plumbingmasters.com',
    description: 'Emergency plumbing and drain cleaning services.',
    tags: ['plumbing', 'emergency', 'drain-cleaning', 'water-heaters'],
    notes: '24/7 emergency service available.',
    referralSource: 'google',
    createdAt: '2023-02-14T11:20:00.000Z',
    updatedAt: '2024-02-25T10:30:00.000Z',
    lastActiveAt: '2024-02-25T10:30:00.000Z',
    contractStartDate: '2023-02-20',
    contractEndDate: '2025-02-20'
  },
  {
    id: 5,
    companyName: 'Creative Designs Studio',
    contactPerson: 'Michael Brown',
    email: 'michael@creativedesigns.com',
    phone: '555-234-5678',
    businessNumber: 'CD987654321',
    businessType: 'llc',
    industry: 'design',
    address: '654 Design Blvd, Miami, FL 33101',
    serviceAreas: ['Florida', 'Georgia', 'Alabama'],
    status: 'active',
    rating: 4.5,
    totalJobs: 95,
    completedJobs: 92,
    paymentTerms: 'net-15',
    hourlyRate: 75,
    projectRate: 5000,
    currency: 'USD',
    insuranceExpiry: '2024-12-31',
    certifications: [
      { id: 1, name: 'Adobe Certified Expert', expiry: '2025-06-30' }
    ],
    preferredContactMethod: 'email',
    availability: 'business-hours',
    website: 'https://creativedesigns.com',
    description: 'Graphic design and branding agency.',
    tags: ['design', 'graphic-design', 'branding', 'marketing'],
    notes: 'Creative team with modern design approach.',
    referralSource: 'social-media',
    createdAt: '2023-07-22T13:10:00.000Z',
    updatedAt: '2024-02-24T15:45:00.000Z',
    lastActiveAt: '2024-02-24T15:45:00.000Z',
    contractStartDate: '2023-07-25',
    contractEndDate: null
  },
  {
    id: 6,
    companyName: 'HVAC Experts',
    contactPerson: 'Sarah Davis',
    email: 'sarah@hvacexperts.com',
    phone: '555-345-6789',
    businessNumber: 'HV123987456',
    businessType: 'corporation',
    industry: 'hvac',
    address: '987 Airflow Rd, Phoenix, AZ 85001',
    serviceAreas: ['Arizona', 'New Mexico', 'Nevada'],
    status: 'active',
    rating: 4.7,
    totalJobs: 275,
    completedJobs: 270,
    paymentTerms: 'net-30',
    hourlyRate: 90,
    projectRate: null,
    currency: 'USD',
    insuranceExpiry: '2025-08-31',
    certifications: [
      { id: 1, name: 'EPA Certification', expiry: '2026-01-31' },
      { id: 2, name: 'NATE Certified', expiry: '2025-05-31' }
    ],
    preferredContactMethod: 'phone',
    availability: '24/7',
    website: 'https://hvacexperts.com',
    description: 'Heating, ventilation, and air conditioning installation and repair.',
    tags: ['hvac', 'heating', 'cooling', 'maintenance'],
    notes: 'Specializes in commercial HVAC systems.',
    referralSource: 'referral',
    createdAt: '2023-04-05T08:45:00.000Z',
    updatedAt: '2024-02-23T12:30:00.000Z',
    lastActiveAt: '2024-02-23T12:30:00.000Z',
    contractStartDate: '2023-04-10',
    contractEndDate: '2025-04-10'
  },
  {
    id: 7,
    companyName: 'Landscape Architects',
    contactPerson: 'David Miller',
    email: 'david@landscapearch.com',
    phone: '555-456-7891',
    businessNumber: 'LA456789123',
    businessType: 'llc',
    industry: 'landscaping',
    address: '147 Greenway St, Denver, CO 80202',
    serviceAreas: ['Colorado', 'Utah', 'Wyoming'],
    status: 'active',
    rating: 4.4,
    totalJobs: 185,
    completedJobs: 180,
    paymentTerms: 'net-30',
    hourlyRate: 65,
    projectRate: null,
    currency: 'USD',
    insuranceExpiry: '2024-10-31',
    certifications: [
      { id: 1, name: 'Landscape Architect License', expiry: '2025-07-31' }
    ],
    preferredContactMethod: 'email',
    availability: 'business-hours',
    website: 'https://landscapearch.com',
    description: 'Professional landscape design and installation.',
    tags: ['landscaping', 'design', 'maintenance', 'irrigation'],
    notes: 'Excellent with xeriscaping projects.',
    referralSource: 'website',
    createdAt: '2023-06-18T15:25:00.000Z',
    updatedAt: '2024-02-22T14:15:00.000Z',
    lastActiveAt: '2024-02-22T14:15:00.000Z',
    contractStartDate: '2023-06-20',
    contractEndDate: null
  },
  {
    id: 8,
    companyName: 'Roofing Solutions',
    contactPerson: 'Jennifer Wilson',
    email: 'jennifer@roofingsolutions.com',
    phone: '555-567-8901',
    businessNumber: 'RS789123456',
    businessType: 'sole-proprietor',
    industry: 'roofing',
    address: '258 Shingle Ave, Dallas, TX 75201',
    serviceAreas: ['Texas', 'Arkansas', 'Mississippi'],
    status: 'suspended',
    rating: 4.2,
    totalJobs: 150,
    completedJobs: 145,
    paymentTerms: 'net-30',
    hourlyRate: 70,
    projectRate: null,
    currency: 'USD',
    insuranceExpiry: '2024-03-31',
    certifications: [
      { id: 1, name: 'Roofing Contractor License', expiry: '2024-12-31' }
    ],
    preferredContactMethod: 'phone',
    availability: 'business-hours',
    website: null,
    description: 'Roof repair, replacement, and maintenance.',
    tags: ['roofing', 'repair', 'installation', 'maintenance'],
    notes: 'Currently suspended due to insurance lapse.',
    referralSource: 'google',
    createdAt: '2023-08-30T10:10:00.000Z',
    updatedAt: '2024-02-21T16:45:00.000Z',
    lastActiveAt: '2024-01-15T14:20:00.000Z',
    contractStartDate: '2023-09-05',
    contractEndDate: null
  },
  {
    id: 9,
    companyName: 'Security Systems Pro',
    contactPerson: 'Christopher Moore',
    email: 'chris@securitypro.com',
    phone: '555-678-9012',
    businessNumber: 'SS456789012',
    businessType: 'corporation',
    industry: 'security',
    address: '369 Secure St, Atlanta, GA 30303',
    serviceAreas: ['Georgia', 'Tennessee', 'South Carolina'],
    status: 'active',
    rating: 4.8,
    totalJobs: 210,
    completedJobs: 208,
    paymentTerms: 'net-30',
    hourlyRate: 110,
    projectRate: null,
    currency: 'USD',
    insuranceExpiry: '2025-09-30',
    certifications: [
      { id: 1, name: 'Security Systems Installer', expiry: '2026-02-28' },
      { id: 2, name: 'Alarm Monitoring Certified', expiry: '2025-08-31' }
    ],
    preferredContactMethod: 'email',
    availability: 'business-hours',
    website: 'https://securitypro.com',
    description: 'Security system installation and monitoring services.',
    tags: ['security', 'alarms', 'cameras', 'monitoring'],
    notes: 'Specializes in smart home security systems.',
    referralSource: 'referral',
    createdAt: '2023-03-12T12:35:00.000Z',
    updatedAt: '2024-02-20T11:20:00.000Z',
    lastActiveAt: '2024-02-20T11:20:00.000Z',
    contractStartDate: '2023-03-15',
    contractEndDate: '2026-03-15'
  },
  {
    id: 10,
    companyName: 'Clean Sweep Services',
    contactPerson: 'Lisa Taylor',
    email: 'lisa@cleansweep.com',
    phone: '555-789-0124',
    businessNumber: 'CS123456780',
    businessType: 'sole-proprietor',
    industry: 'cleaning',
    address: '741 Clean Ave, Seattle, WA 98101',
    serviceAreas: ['Washington', 'Oregon'],
    status: 'pending',
    rating: null,
    totalJobs: 0,
    completedJobs: 0,
    paymentTerms: 'net-15',
    hourlyRate: 45,
    projectRate: null,
    currency: 'USD',
    insuranceExpiry: '2024-12-31',
    certifications: [
      { id: 1, name: 'Cleaning Industry Certified', expiry: '2025-06-30' }
    ],
    preferredContactMethod: 'sms',
    availability: 'business-hours',
    website: null,
    description: 'Commercial and residential cleaning services.',
    tags: ['cleaning', 'janitorial', 'residential', 'commercial'],
    notes: 'New contractor awaiting background check.',
    referralSource: 'website',
    createdAt: '2024-01-10T09:15:00.000Z',
    updatedAt: '2024-01-10T09:15:00.000Z',
    lastActiveAt: null,
    contractStartDate: null,
    contractEndDate: null
  },
  {
    id: 11,
    companyName: 'Concrete Masters',
    contactPerson: 'Daniel Anderson',
    email: 'daniel@concretemasters.com',
    phone: '555-890-1234',
    businessNumber: 'CM789012345',
    businessType: 'corporation',
    industry: 'concrete',
    address: '852 Cement Rd, Las Vegas, NV 89101',
    serviceAreas: ['Nevada', 'Arizona', 'California'],
    status: 'active',
    rating: 4.3,
    totalJobs: 195,
    completedJobs: 190,
    paymentTerms: 'net-30',
    hourlyRate: 85,
    projectRate: null,
    currency: 'USD',
    insuranceExpiry: '2025-01-31',
    certifications: [
      { id: 1, name: 'Concrete Finisher Certified', expiry: '2025-10-31' }
    ],
    preferredContactMethod: 'phone',
    availability: 'business-hours',
    website: 'https://concretemasters.com',
    description: 'Concrete pouring, finishing, and repair services.',
    tags: ['concrete', 'foundation', 'driveway', 'sidewalk'],
    notes: 'Specializes in decorative concrete work.',
    referralSource: 'google',
    createdAt: '2023-05-22T16:40:00.000Z',
    updatedAt: '2024-02-19T13:25:00.000Z',
    lastActiveAt: '2024-02-19T13:25:00.000Z',
    contractStartDate: '2023-05-25',
    contractEndDate: null
  },
  {
    id: 12,
    companyName: 'Carpentry Works',
    contactPerson: 'Amanda Thomas',
    email: 'amanda@carpentryworks.com',
    phone: '555-901-2345',
    businessNumber: 'CW234567890',
    businessType: 'sole-proprietor',
    industry: 'carpentry',
    address: '963 Woodwork Ln, Boston, MA 02108',
    serviceAreas: ['Massachusetts', 'New Hampshire', 'Rhode Island'],
    status: 'active',
    rating: 4.6,
    totalJobs: 175,
    completedJobs: 172,
    paymentTerms: 'net-30',
    hourlyRate: 75,
    projectRate: null,
    currency: 'USD',
    insuranceExpiry: '2024-11-30',
    certifications: [
      { id: 1, name: 'Journeyman Carpenter', expiry: '2025-09-30' }
    ],
    preferredContactMethod: 'phone',
    availability: 'business-hours',
    website: null,
    description: 'Custom carpentry and woodworking services.',
    tags: ['carpentry', 'woodworking', 'cabinets', 'furniture'],
    notes: 'Excellent custom furniture maker.',
    referralSource: 'referral',
    createdAt: '2023-07-30T14:05:00.000Z',
    updatedAt: '2024-02-18T10:40:00.000Z',
    lastActiveAt: '2024-02-18T10:40:00.000Z',
    contractStartDate: '2023-08-05',
    contractEndDate: null
  },
  {
    id: 13,
    companyName: 'Glass & Mirror Experts',
    contactPerson: 'James Jackson',
    email: 'james@glassexperts.com',
    phone: '555-012-3456',
    businessNumber: 'GM345678901',
    businessType: 'llc',
    industry: 'glass',
    address: '159 Glass Ave, Philadelphia, PA 19102',
    serviceAreas: ['Pennsylvania', 'New Jersey', 'Delaware'],
    status: 'inactive',
    rating: 4.1,
    totalJobs: 120,
    completedJobs: 118,
    paymentTerms: 'net-30',
    hourlyRate: 70,
    projectRate: null,
    currency: 'USD',
    insuranceExpiry: '2023-12-31',
    certifications: [
      { id: 1, name: 'Glass Installation Certified', expiry: '2024-08-31' }
    ],
    preferredContactMethod: 'phone',
    availability: 'business-hours',
    website: 'https://glassexperts.com',
    description: 'Glass installation, repair, and mirror hanging services.',
    tags: ['glass', 'mirrors', 'windows', 'showers'],
    notes: 'Inactive due to business closure.',
    referralSource: 'google',
    createdAt: '2023-02-08T11:50:00.000Z',
    updatedAt: '2024-01-28T13:15:00.000Z',
    lastActiveAt: '2023-12-15T10:30:00.000Z',
    contractStartDate: '2023-02-10',
    contractEndDate: '2023-12-31'
  },
  {
    id: 14,
    companyName: 'Digital Marketing Pros',
    contactPerson: 'Jessica White',
    email: 'jessica@digitalmarketingpros.com',
    phone: '555-123-4578',
    businessNumber: 'DM456789123',
    businessType: 'llc',
    industry: 'marketing',
    address: '753 Marketing St, Austin, TX 73301',
    serviceAreas: ['Texas', 'National'],
    status: 'active',
    rating: 4.7,
    totalJobs: 85,
    completedJobs: 83,
    paymentTerms: 'net-15',
    hourlyRate: 95,
    projectRate: 3000,
    currency: 'USD',
    insuranceExpiry: '2025-04-30',
    certifications: [
      { id: 1, name: 'Google Ads Certified', expiry: '2025-12-31' },
      { id: 2, name: 'Facebook Blueprint Certified', expiry: '2025-10-31' }
    ],
    preferredContactMethod: 'email',
    availability: 'business-hours',
    website: 'https://digitalmarketingpros.com',
    description: 'Digital marketing and social media management services.',
    tags: ['marketing', 'social-media', 'seo', 'advertising'],
    notes: 'Excellent track record with e-commerce clients.',
    referralSource: 'social-media',
    createdAt: '2023-09-14T10:25:00.000Z',
    updatedAt: '2024-02-17T14:50:00.000Z',
    lastActiveAt: '2024-02-17T14:50:00.000Z',
    contractStartDate: '2023-09-20',
    contractEndDate: null
  },
  {
    id: 15,
    companyName: 'Appliance Repair Specialists',
    contactPerson: 'Matthew Harris',
    email: 'matt@appliancefix.com',
    phone: '555-234-5689',
    businessNumber: 'AR567890123',
    businessType: 'sole-proprietor',
    industry: 'appliance-repair',
    address: '951 Appliance Rd, Charlotte, NC 28202',
    serviceAreas: ['North Carolina', 'South Carolina'],
    status: 'active',
    rating: 4.4,
    totalJobs: 310,
    completedJobs: 305,
    paymentTerms: 'net-15',
    hourlyRate: 75,
    projectRate: null,
    currency: 'USD',
    insuranceExpiry: '2024-09-30',
    certifications: [
      { id: 1, name: 'Appliance Repair Technician', expiry: '2025-07-31' }
    ],
    preferredContactMethod: 'phone',
    availability: 'business-hours',
    website: null,
    description: 'Repair of all major household appliances.',
    tags: ['appliance-repair', 'refrigerator', 'washer', 'dryer'],
    notes: 'Same-day service available.',
    referralSource: 'google',
    createdAt: '2023-04-25T13:30:00.000Z',
    updatedAt: '2024-02-16T09:45:00.000Z',
    lastActiveAt: '2024-02-16T09:45:00.000Z',
    contractStartDate: '2023-05-01',
    contractEndDate: null
  },
  {
    id: 16,
    companyName: 'Flooring Innovations',
    contactPerson: 'Ashley Martin',
    email: 'ashley@flooringinnovations.com',
    phone: '555-345-6790',
    businessNumber: 'FI678901234',
    businessType: 'corporation',
    industry: 'flooring',
    address: '357 Floor St, Nashville, TN 37201',
    serviceAreas: ['Tennessee', 'Kentucky', 'Alabama'],
    status: 'pending',
    rating: null,
    totalJobs: 0,
    completedJobs: 0,
    paymentTerms: 'net-30',
    hourlyRate: 65,
    projectRate: null,
    currency: 'USD',
    insuranceExpiry: '2024-12-31',
    certifications: [
      { id: 1, name: 'Flooring Installer Certified', expiry: '2025-11-30' }
    ],
    preferredContactMethod: 'email',
    availability: 'business-hours',
    website: 'https://flooringinnovations.com',
    description: 'Hardwood, laminate, and tile flooring installation.',
    tags: ['flooring', 'hardwood', 'tile', 'laminate'],
    notes: 'Awaiting final license approval.',
    referralSource: 'website',
    createdAt: '2024-01-16T08:55:00.000Z',
    updatedAt: '2024-01-16T08:55:00.000Z',
    lastActiveAt: null,
    contractStartDate: null,
    contractEndDate: null
  },
  {
    id: 17,
    companyName: 'Painting Pros',
    contactPerson: 'Joshua Thompson',
    email: 'josh@paintingpros.com',
    phone: '555-456-7801',
    businessNumber: 'PP789012345',
    businessType: 'sole-proprietor',
    industry: 'painting',
    address: '486 Paint Ave, San Diego, CA 92101',
    serviceAreas: ['California'],
    status: 'active',
    rating: 4.5,
    totalJobs: 230,
    completedJobs: 225,
    paymentTerms: 'net-30',
    hourlyRate: 60,
    projectRate: null,
    currency: 'USD',
    insuranceExpiry: '2025-05-31',
    certifications: [
      { id: 1, name: 'Lead-Safe Certified', expiry: '2025-12-31' }
    ],
    preferredContactMethod: 'sms',
    availability: 'business-hours',
    website: null,
    description: 'Interior and exterior painting services.',
    tags: ['painting', 'interior', 'exterior', 'residential'],
    notes: 'Uses eco-friendly paints.',
    referralSource: 'referral',
    createdAt: '2023-06-05T15:15:00.000Z',
    updatedAt: '2024-02-15T16:30:00.000Z',
    lastActiveAt: '2024-02-15T16:30:00.000Z',
    contractStartDate: '2023-06-10',
    contractEndDate: null
  },
  {
    id: 18,
    companyName: 'Data Analytics Consultants',
    contactPerson: 'Samantha Garcia',
    email: 'samantha@dataconsultants.com',
    phone: '555-567-8912',
    businessNumber: 'DA890123456',
    businessType: 'llc',
    industry: 'data-analytics',
    address: '624 Data Dr, Portland, OR 97201',
    serviceAreas: ['Oregon', 'Washington', 'California'],
    status: 'active',
    rating: 4.9,
    totalJobs: 65,
    completedJobs: 63,
    paymentTerms: 'net-15',
    hourlyRate: 150,
    projectRate: 10000,
    currency: 'USD',
    insuranceExpiry: '2025-07-31',
    certifications: [
      { id: 1, name: 'Data Science Certified', expiry: '2026-01-31' }
    ],
    preferredContactMethod: 'email',
    availability: 'business-hours',
    website: 'https://dataconsultants.com',
    description: 'Data analytics and business intelligence consulting.',
    tags: ['data-analytics', 'consulting', 'bi', 'machine-learning'],
    notes: 'Specializes in healthcare data analytics.',
    referralSource: 'linkedin',
    createdAt: '2023-08-12T12:40:00.000Z',
    updatedAt: '2024-02-14T14:20:00.000Z',
    lastActiveAt: '2024-02-14T14:20:00.000Z',
    contractStartDate: '2023-08-15',
    contractEndDate: null
  },
  {
    id: 19,
    companyName: 'Masonry Masters',
    contactPerson: 'Andrew Martinez',
    email: 'andrew@masonrymasters.com',
    phone: '555-678-9023',
    businessNumber: 'MM901234567',
    businessType: 'corporation',
    industry: 'masonry',
    address: '759 Brick St, Denver, CO 80203',
    serviceAreas: ['Colorado', 'Utah'],
    status: 'inactive',
    rating: 4.2,
    totalJobs: 140,
    completedJobs: 138,
    paymentTerms: 'net-30',
    hourlyRate: 80,
    projectRate: null,
    currency: 'USD',
    insuranceExpiry: '2023-09-30',
    certifications: [
      { id: 1, name: 'Master Mason License', expiry: '2024-06-30' }
    ],
    preferredContactMethod: 'phone',
    availability: 'business-hours',
    website: null,
    description: 'Brick and stone masonry work.',
    tags: ['masonry', 'brick', 'stone', 'chimney'],
    notes: 'Seasonal business - closed for winter.',
    referralSource: 'google',
    createdAt: '2023-03-10T09:20:00.000Z',
    updatedAt: '2024-02-13T10:30:00.000Z',
    lastActiveAt: '2023-11-30T15:45:00.000Z',
    contractStartDate: '2023-03-15',
    contractEndDate: '2023-11-30'
  },
  {
    id: 20,
    companyName: 'Web Development Studio',
    contactPerson: 'Megan Robinson',
    email: 'megan@webdevstudio.com',
    phone: '555-789-0134',
    businessNumber: 'WD012345678',
    businessType: 'llc',
    industry: 'web-development',
    address: '852 Code Ave, Salt Lake City, UT 84101',
    serviceAreas: ['Utah', 'Idaho', 'National'],
    status: 'active',
    rating: 4.8,
    totalJobs: 110,
    completedJobs: 108,
    paymentTerms: 'net-15',
    hourlyRate: 100,
    projectRate: 7500,
    currency: 'USD',
    insuranceExpiry: '2025-06-30',
    certifications: [
      { id: 1, name: 'Full Stack Developer', expiry: '2025-12-31' }
    ],
    preferredContactMethod: 'email',
    availability: 'business-hours',
    website: 'https://webdevstudio.com',
    description: 'Custom website development and e-commerce solutions.',
    tags: ['web-development', 'e-commerce', 'react', 'nodejs'],
    notes: 'Specializes in React and Node.js applications.',
    referralSource: 'website',
    createdAt: '2023-10-05T16:05:00.000Z',
    updatedAt: '2024-02-12T12:15:00.000Z',
    lastActiveAt: '2024-02-12T12:15:00.000Z',
    contractStartDate: '2023-10-10',
    contractEndDate: null
  },
  {
    id: 21,
    companyName: 'Pest Control Solutions',
    contactPerson: 'Kevin Clark',
    email: 'kevin@pestcontrol.com',
    phone: '555-890-1245',
    businessNumber: 'PC123456789',
    businessType: 'corporation',
    industry: 'pest-control',
    address: '147 Bugfree St, Orlando, FL 32801',
    serviceAreas: ['Florida'],
    status: 'active',
    rating: 4.6,
    totalJobs: 420,
    completedJobs: 415,
    paymentTerms: 'net-30',
    hourlyRate: 70,
    projectRate: null,
    currency: 'USD',
    insuranceExpiry: '2025-03-31',
    certifications: [
      { id: 1, name: 'Pest Control Operator', expiry: '2025-08-31' },
      { id: 2, name: 'Termite Specialist', expiry: '2025-05-31' }
    ],
    preferredContactMethod: 'phone',
    availability: 'business-hours',
    website: 'https://pestcontrol.com',
    description: 'Residential and commercial pest control services.',
    tags: ['pest-control', 'termite', 'exterminator', 'mosquito'],
    notes: 'Eco-friendly treatment options available.',
    referralSource: 'google',
    createdAt: '2023-01-15T14:30:00.000Z',
    updatedAt: '2024-02-11T12:45:000Z',
    lastActiveAt: '2024-02-11T12:45:00.000Z',
    contractStartDate: '2023-01-20',
    contractEndDate: '2026-01-20'
  },
  {
    id: 22,
    companyName: 'Event Planning Pros',
    contactPerson: 'Nicole Rodriguez',
    email: 'nicole@eventpros.com',
    phone: '555-901-2356',
    businessNumber: 'EP234567890',
    businessType: 'llc',
    industry: 'event-planning',
    address: '258 Event Ave, Miami, FL 33128',
    serviceAreas: ['Florida', 'Georgia'],
    status: 'pending',
    rating: null,
    totalJobs: 0,
    completedJobs: 0,
    paymentTerms: 'net-15',
    hourlyRate: 85,
    projectRate: 5000,
    currency: 'USD',
    insuranceExpiry: '2024-12-31',
    certifications: [
      { id: 1, name: 'Event Planning Certified', expiry: '2025-10-31' }
    ],
    preferredContactMethod: 'email',
    availability: 'business-hours',
    website: 'https://eventpros.com',
    description: 'Full-service event planning and coordination.',
    tags: ['event-planning', 'weddings', 'corporate', 'parties'],
    notes: 'New company - excellent portfolio.',
    referralSource: 'social-media',
    createdAt: '2024-01-22T11:10:00.000Z',
    updatedAt: '2024-01-22T11:10:00.000Z',
    lastActiveAt: null,
    contractStartDate: null,
    contractEndDate: null
  },
  {
    id: 23,
    companyName: 'Audio Visual Specialists',
    contactPerson: 'Brian Lewis',
    email: 'brian@avspecialists.com',
    phone: '555-012-3467',
    businessNumber: 'AV345678901',
    businessType: 'corporation',
    industry: 'audio-visual',
    address: '369 AV St, Los Angeles, CA 90012',
    serviceAreas: ['California', 'Nevada'],
    status: 'active',
    rating: 4.7,
    totalJobs: 95,
    completedJobs: 93,
    paymentTerms: 'net-30',
    hourlyRate: 95,
    projectRate: 8000,
    currency: 'USD',
    insuranceExpiry: '2025-04-30',
    certifications: [
      { id: 1, name: 'AV Installer Certified', expiry: '2025-11-30' }
    ],
    preferredContactMethod: 'phone',
    availability: 'business-hours',
    website: 'https://avspecialists.com',
    description: 'Audio visual system design and installation.',
    tags: ['audio-visual', 'sound-systems', 'video', 'conference'],
    notes: 'Specializes in corporate conference rooms.',
    referralSource: 'referral',
    createdAt: '2023-07-07T10:45:00.000Z',
    updatedAt: '2024-02-10T15:30:00.000Z',
    lastActiveAt: '2024-02-10T15:30:00.000Z',
    contractStartDate: '2023-07-10',
    contractEndDate: null
  },
  {
    id: 24,
    companyName: 'Heavy Equipment Operators',
    contactPerson: 'Stephanie Lee',
    email: 'stephanie@heavyeq.com',
    phone: '555-123-4589',
    businessNumber: 'HE456789012',
    businessType: 'corporation',
    industry: 'heavy-equipment',
    address: '741 Equipment Rd, Phoenix, AZ 85004',
    serviceAreas: ['Arizona', 'New Mexico'],
    status: 'active',
    rating: 4.5,
    totalJobs: 180,
    completedJobs: 176,
    paymentTerms: 'net-30',
    hourlyRate: 120,
    projectRate: null,
    currency: 'USD',
    insuranceExpiry: '2025-05-31',
    certifications: [
      { id: 1, name: 'Heavy Equipment Operator', expiry: '2025-09-30' },
      { id: 2, name: 'CDL License', expiry: '2026-01-31' }
    ],
    preferredContactMethod: 'phone',
    availability: 'business-hours',
    website: 'https://heavyeq.com',
    description: 'Heavy equipment operation and excavation services.',
    tags: ['heavy-equipment', 'excavation', 'grading', 'demolition'],
    notes: 'Owns fleet of excavators and bulldozers.',
    referralSource: 'google',
    createdAt: '2023-05-15T13:20:00.000Z',
    updatedAt: '2024-02-09T15:10:00.000Z',
    lastActiveAt: '2024-02-09T15:10:00.000Z',
    contractStartDate: '2023-05-20',
    contractEndDate: '2026-05-20'
  },
  {
    id: 25,
    companyName: 'Solar Energy Installers',
    contactPerson: 'Jonathan Walker',
    email: 'jonathan@solarenergy.com',
    phone: '555-234-5690',
    businessNumber: 'SE567890123',
    businessType: 'corporation',
    industry: 'solar',
    address: '852 Solar Ave, San Antonio, TX 78205',
    serviceAreas: ['Texas', 'Oklahoma', 'Louisiana'],
    status: 'inactive',
    rating: 4.3,
    totalJobs: 75,
    completedJobs: 73,
    paymentTerms: 'net-30',
    hourlyRate: 95,
    projectRate: 20000,
    currency: 'USD',
    insuranceExpiry: '2023-11-30',
    certifications: [
      { id: 1, name: 'Solar Installer Certified', expiry: '2024-08-31' }
    ],
    preferredContactMethod: 'email',
    availability: 'business-hours',
    website: 'https://solarenergy.com',
    description: 'Solar panel installation and maintenance.',
    tags: ['solar', 'renewable-energy', 'panels', 'installation'],
    notes: 'Inactive due to market conditions.',
    referralSource: 'website',
    createdAt: '2023-06-25T08:35:00.000Z',
    updatedAt: '2024-01-25T09:25:00.000Z',
    lastActiveAt: '2023-12-20T14:15:00.000Z',
    contractStartDate: '2023-07-01',
    contractEndDate: '2023-12-31'
  }
];

module.exports = contractors;